name: Build and deploy changes Umbraco V8.1

on:
  workflow_call:
    inputs:
      organization-name:
        required: true
        type: string
      project-name:
        required: true
        type: string
      build-configuration:
        required: true
        default: 'release'
        type: string
      csproj-path:
        required: true
        type: string
      site-folder-ending:
        description: 'The folder suffix to copy files from (e.g., .web or .site)'
        required: true
        default: '.web'
        type: string
                
### Some environment variables to ease use and keep oversight        
env:
  app-path: ${{ github.workspace }}\${{ inputs.organization-name }}.${{ inputs.project-name }}.${{ inputs.site-folder-ending }}
        
jobs:
  Checkout-source:
    name: Checkout source code
    runs-on: [self-hosted, axendo]
    steps:
    - name: git configure long path
      run: git config --global core.longpaths true
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0 #fetch-depth 0 indicates fetching all history, this is needed for frontend en vue caching

  Build-NET:
    name: Build & Publish .NET
    needs: Checkout-source
    runs-on: [self-hosted, axendo]
    steps:
    - name: Setup .NET
      uses: AxendoNL/dotnet-build-action@v8.1
      with:
        organization-name: ${{ inputs.organization-name }}
        project-name: ${{ inputs.project-name }}
        build-configuration: ${{ inputs.build-configuration }}
        csproj-path: ${{ inputs.csproj-path }}
        token: ${{ secrets.NUGET_PAT }}
        site-folder-ending: ${{ inputs.site-folder-ending }}
  
  Cleanup:
    name: cleanup files
    needs: Build-NET
    if: always()
    runs-on: [self-hosted, axendo]
    steps:
    - name: Delete GitHub workspace
      run: Remove-Item -Recurse -Force ./*