name: Build and deploy changes Umbraco V8

on:
  workflow_call:
    inputs:
      front-end-directory:
        required: true
        type: string
      vue-directory:
        required: true
        type: string
      organization-name:
        required: true
        type: string
      project-name:
        required: true
        type: string
      build-configuration:
        required: true
        default: 'release'
        type: string
      csproj-path:
        required: true
        type: string

jobs:
  Checkout-source:
    name: Checkout source code
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

  Build-frontend:
    name: Build Frontend
    needs: Checkout-source
    runs-on: self-hosted
    steps:
      - name: build the frontend
        uses: AxendoNL/build-frontend-action@umbraco-v8
        with:
          vue-dir: ${{ inputs.front-end-directory }}
  
  Build-vue:
    name: Build Vue
    needs: Build-frontend
    runs-on: self-hosted
    steps:
      - name: build the frontend
        uses: AxendoNL/build-vue-action@master
        with:
          frontend-dir: ${{ inputs.vue-directory }}

  # Build-NET:
  #   name: Build & Publish .NET
  #   needs: Build-frontend
  #   runs-on: self-hosted
  #   steps:
  #   - name: Setup .NET
  #     uses: AxendoNL/dotnet-build-action@umbraco-v8
  #     with:
  #       organization-name: ${{ inputs.organization-name }}
  #       project-name: ${{ inputs.project-name }}
  #       build-configuration: ${{ inputs.build-configuration }}
  #       csproj-path: ${{ inputs.csproj-path }}