name: Build and deploy changes Umbraco V9 - Cloud

on:
  workflow_call:
    inputs:
      front-end-directory:
        required: true
        type: string
      cd-path:
        required: false
        type: string
      organization-name:
        required: true
        type: string
      project-name:
        required: true
        type: string
      build-configuration:
        required: true
        default: 'release'
        type: string
      csproj-path:
        required: true
        type: string
    secrets:
      cloud-repository-url:
        required: true

jobs:
  Checkout-source:
    name: Checkout source code
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

  Build-frontend:
    name: Build Frontend
    needs: Checkout-source
    runs-on: self-hosted
    steps:
      - name: build the frontend
        uses: AxendoNL/build-frontend-action@umbraco-v9
        with:
          front-end-directory: ${{ inputs.front-end-directory }}
          cd-path: ${{ inputs.cd-path }}

  Build-NET:
    name: Build & Publish .NET
    needs: Build-frontend
    if: github.ref_name != 'master'
    runs-on: self-hosted
    steps:
    - name: Setup .NET
      uses: AxendoNL/dotnet-build-action@umbraco-v9
      with:
        organization-name: ${{ inputs.organization-name }}
        project-name: ${{ inputs.project-name }}
        build-configuration: ${{ inputs.build-configuration }}
        csproj-path: ${{ inputs.csproj-path }}

  Sync-and-push-to-cloud: 
    name: Sync and push to cloud
    if: github.ref_name == 'master'
    needs: Build-frontend
    runs-on: self-hosted

    steps:
    - uses: AxendoNL/sync-changes-to-cloud-action@umbraco-v9
      with:
        cloud-repository-url: ${{secrets.cloud-repository-url}}
        from-dir: ./
        to-dir: ../cloud-repository

  cleanup:
    if: ${{ always() }}
    needs: [Sync-and-push-to-cloud]
    runs-on: self-hosted
    steps:
      - uses: AxendoNL/sync-cleanup-action@umbraco-v9