name: Build and deploy changes Umbraco V9.1 - Cloud

on:
  workflow_call:
    inputs:
      frontend-directory:
        required: false
        type: string
      cd-path:
        required: false
        type: string
      vue-directory:
        required: false
        type: string
      cd-path-vue:
        required: false
        type: string
      organization-name:
        required: true
        type: string
      project-name:
        required: true
        type: string
      build-configuration:
        required: true
        default: 'release'
        type: string
      csproj-path:
        required: true
        type: string
    secrets:
      cloud-repository-url:
        required: true
        
### Some environment variables to ease use and keep oversight         
env:
  app-path: ${{ github.workspace }}\Axendo.Umb.${{ inputs.organization-name }}.${{ inputs.project-name }}.Web

jobs:
  Checkout-source:
    name: Checkout source code
    runs-on: self-hosted
    steps:
    - name: git configure long path
      run: git config --global core.longpaths true
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0 #fetch-depth 0 indicates fetching all history, this is needed for frontend en vue caching

  Build-frontend:
    if: ${{ inputs.frontend-directory }}
    name: Build Frontend
    needs: Checkout-source
    runs-on: self-hosted
    steps:
      - name: build the frontend
        uses: AxendoNL/build-frontend-action@umbraco-v9.1
        with:
          frontend-directory: ${{ inputs.frontend-directory }}
          cd-path: ${{ inputs.cd-path }}
          app-path: ${{ env.app-path }}

  Build-vue:
    if:  ${{ inputs.vue-directory }}
    name: Build Vue
    needs: Build-frontend         
    runs-on: self-hosted
    steps:
      - name: Build vue apps
        uses: AxendoNL/build-vue-action@umbraco-v9.1
        with:
          vue-directory: ${{ inputs.vue-directory }}
          cd-path-vue: ${{ inputs.cd-path-vue }}
          app-path: ${{ env.app-path }}

  Build-NET:
    name: Build & Publish .NET
    needs: Build-vue
    if: github.ref_name != 'master'
    runs-on: self-hosted
    steps:
    - name: Setup .NET
      uses: AxendoNL/dotnet-build-action@umbraco-v9
      with:
        organization-name: ${{ inputs.organization-name }}
        project-name: ${{ inputs.project-name }}
        build-configuration: ${{ inputs.build-configuration }}
        csproj-path: ${{ inputs.csproj-path }}

  Sync-and-push-to-cloud: 
    name: Sync and push to cloud
    if: github.ref_name == 'master'
    needs: Build-frontend
    runs-on: self-hosted

    steps:
    - uses: AxendoNL/sync-changes-to-cloud-action@umbraco-v9
      with:
        cloud-repository-url: ${{secrets.cloud-repository-url}}
        from-dir: ./
        to-dir: ../cloud-repository

  cleanup:
    if: ${{ always() }}
    needs: [Sync-and-push-to-cloud]
    runs-on: self-hosted
    steps:
      - uses: AxendoNL/sync-cleanup-action@umbraco-v9