name: Build and deploy changes Umbraco V11 - Cloud

on:
  workflow_call:
    inputs:
      frontend-directory:
        required: false
        type: string
      vue-directory:
        required: false
        type: string
      organization-name:
        required: true
        type: string
      project-name:
        required: true
        type: string
      build-configuration:
        required: true
        default: 'release'
        type: string
      csproj-path:
        required: true
        type: string

### Some environment variables to ease use and keep oversight        
env:
  app-path: ${{ github.workspace }}\Axendo.Umb.${{ inputs.organization-name }}.${{ inputs.project-name }}.Web

jobs:
  Checkout-source:
    name: Checkout source code
    runs-on: [self-hosted, axendo]
    steps:
    - name: git configure long path
      run: git config --global core.longpaths true
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0 #fetch-depth 0 indicates fetching all history, this is needed for frontend en vue caching

  Build-frontend:
    if: ${{ inputs.frontend-directory }}
    name: Build Frontend
    needs: Checkout-source
    runs-on: [self-hosted, axendo]
    steps:
      - name: Build frontend with Webpack
        uses: AxendoNL/webpack-action@v1.2.0
        with:
          directory: ${{ inputs.frontend-directory }}
          output-folder: '${{ env.app-path }}\\wwwroot\\assets'
          node-version: '${{vars.FRONTEND_NODE_VERSION}}'
          
  Build-vue:
    name: Build Vue
    needs: Build-frontend
    if: always() && ${{ inputs.vue-directory }} && (needs.build-frontend.result == 'success' || needs.build-frontend.result == 'skipped')
    runs-on: [self-hosted, axendo]
    steps:
      - name: Build vue apps
        uses: AxendoNL/webpack-action@v1.2.0
        with:
          directory: ${{ inputs.vue-directory }}
          output-folder: '${{ env.app-path }}\\wwwroot\\vue-apps'
          node-version: '${{vars.VUE_NODE_VERSION}}'

  Build-NET:
    name: Build & Publish .NET
    needs: Build-vue
    if: always() && github.ref_name != 'master' && (needs.build-vue.result == 'success' || needs.build-vue.result == 'skipped')
    runs-on: [self-hosted, axendo]
    steps:
    - name: Setup .NET
      uses: AxendoNL/dotnet-build-action@v11
      with:
        organization-name: ${{ inputs.organization-name }}
        project-name: ${{ inputs.project-name }}
        build-configuration: ${{ inputs.build-configuration }}
        csproj-path: ${{ inputs.csproj-path }}
        token: ${{ secrets.NUGET_PAT }}

  Sync-and-push-to-cloud: 
    name: Sync and push to cloud
    if: always() && github.ref_name == 'master' && (needs.build-vue.result == 'success' || needs.build-vue.result == 'skipped')
    needs: Build-Vue
    runs-on: [self-hosted, axendo]
    steps:
    - name: Add GitHub PAT to nuget.config
      run: (Get-Content -path .\NuGet.config -Raw) -replace '{PAT}','${{ secrets.NUGET_PAT }}' | Set-Content -Path .\NuGet.config
      shell: powershell
    - uses: oNaiPs/secrets-to-env-action@v1.3 # Load VARS
      with:
        secrets: ${{ toJSON(vars) }}
    - uses: AxendoNL/sync-changes-to-cloud-action@umbraco-v9
      with:
        cloud-repository-url: 'https://${{secrets.UMBRACO_CLOUD_USERNAME}}:${{secrets.UMBRACO_CLOUD_PASSWORD}}@${{secrets.CLOUD_REPOSITORY_URL}}'
        from-dir: ./
        to-dir: ../cloud-repository

  cleanup:
    if: always() && vars.SKIP_CLEANUP != 'true'
    needs: [Sync-and-push-to-cloud]
    runs-on: [self-hosted, axendo]
    steps:
      - name: Delete sync folder en files
        uses: AxendoNL/sync-cleanup-action@v9
      - name: Delete GitHub workspace
        run: Remove-Item -Recurse -Force ./*
