name: Build and deploy changes Umbraco V12

on:
  workflow_call:
    inputs:
      frontend-directory:
        required: false
        type: string
      vue-directory:
        required: false
        type: string
      organization-name:
        required: true
        type: string
      project-name:
        required: true
        type: string
      build-configuration:
        required: true
        default: 'release'
        type: string
      csproj-path:
        required: true
        type: string
      runner-platform:
        required: true
        type: string
        default: 'self-hosted'

### Some environment variables to ease use and keep oversight        
env:
  app-path: ${{ github.workspace }}\Axendo.Umb.${{ inputs.organization-name }}.${{ inputs.project-name }}.Web

jobs:
  Build:
    name: Checkout source code
    runs-on: ["${{ inputs.runner-platform }}"]
    steps:
    - name: configure safe dir
      run: git config --global --add safe.directory ${{ github.workspace }}
    - name: git configure long path
      run: git config --global core.longpaths true
    - uses: actions/checkout@v4.1.1
      with: 
        fetch-depth: 0 #fetch-depth 0 indicates fetching all history, this is needed for frontend en vue caching
    - name: Build Frontend
      if: ${{ inputs.frontend-directory }}
      uses: AxendoNL/webpack-action@v1.0.0
      with:
        directory: ${{ inputs.frontend-directory }}
        output-folder: '${{ env.app-path }}\\wwwroot\\assets'
    - name: Build Vue apps
      if: ${{ inputs.vue-directory }}
      uses: AxendoNL/webpack-action@v1.0.0
      with:
        directory: ${{ inputs.vue-directory }}
        output-folder: '${{ env.app-path }}\\wwwroot\\vue-apps'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - name: Add GitHub PAT to nuget.config
      run: (Get-Content -path .\NuGet.config -Raw) -replace '{PAT}','${{ secrets.NUGET_PAT }}' | Set-Content -Path .\NuGet.config
      shell: powershell
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './**/appsettings.json'
      env:
        Umbraco.CMS.RuntimeMinification.version: ${{github.run_number}}
    - name: Dotnet publish
      run: dotnet publish ${{ inputs.csproj-path }} -c Release -o ./myapp
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ./myapp