name: Deploy to Azure

on:
  workflow_call:
    inputs:
      runner-platform:
        required: true
        type: string
        default: 'self-hosted'
      app-name:
        required: true
        type: string
      slot-name:
        required: true
        type: string
    secrets:
      publish-profile:
        required: true

jobs:
  Prepare:
    name: Prepare working directory
    runs-on: ["${{ inputs.runner-platform }}"]
    steps:
    - name: Delete GitHub workspace
      run: Remove-Item -Recurse -Force ./*
      
  Deploy:
    name: Deploy to Azure
    needs: Prepare
    runs-on: ["${{ inputs.runner-platform }}"]
    environment:
      name: ${{ inputs.slot-name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: .net-app
          path: ./../artifact
      - name: Compress
        run: Compress-Archive -Path ./../artifact* -DestinationPath ./../artifact.zip
        shell: powershell
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3.0.2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name }}
          publish-profile: ${{ secrets.publish-profile }}
          package: ./../artifact.zip  # Ensure this matches the path where you saved the .zip
          type: zip
          clean: true
          restart: true