name: Deploy to Azure

on:
  workflow_call:
    inputs:
      runner-platform:
        required: true
        type: string
        default: 'self-hosted'
      app-name:
        required: true
        type: string
      slot-name:
        required: true
        type: string

jobs:
  Deploy:
    name: Deploy to Azure
    runs-on: ["${{ inputs.runner-platform }}"]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4630A39CA5BE4167AA2E5101E9E42902 }}
          package: .