name: Deploy to Azure

on:
  workflow_call:
    inputs:
      runner-platform:
        required: true
        type: string
        default: 'self-hosted'
      app-name:
        required: true
        type: string
      slot-name:
        required: true
        type: string
    secrets:
      publish-profile:
        required: true

jobs:
  Deploy:
    name: Deploy to Azure
    runs-on: ["${{ inputs.runner-platform }}"]
    environment:
      name: ${{ inputs.slot-name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v4.1.7
      #   with:
      #     name: .net-app
      # - name: Extract artifact
      #   run: Expand-Archive -Path artifact.zip -DestinationPath ./todeploy
      #   shell: powershell
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name }}
          publish-profile: ${{ secrets.publish-profile }}
          package: artifact.zip
          type: zip
          clean: true
          restart: true