name: Synchronize cloud changes

on:
  workflow_call:
    inputs:
      web-directory:
        required: true
        type: string
    secrets:
      cloud-repository-url:
        required: true

jobs:
  Synchronize:
    name: Synchronize
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: AxendoNL/sync-changes-from-cloud-action@umbraco-v8
        with:
          cloud-repository-url: ${{secrets.cloud-repository-url}}
          web-directory: ${{inputs.web-directory}}
  Cleanup:
    if: ${{ always() }}
    needs: Synchronize
    runs-on: self-hosted
    steps:
      - uses: AxendoNL/sync-cleanup-action@umbraco-v8