name: Synchronize cloud changes Umbraco V8.x

on:
  workflow_call:
    inputs:
      web-directory:
        required: true
        type: string
    secrets:
      cloud-repository-url:
        required: true
      umbraco-cloud-username:
        required: true
      umbraco-cloud-password:
        required: true

jobs:
  Synchronize:
    name: Synchronize
    runs-on: [self-hosted, axendo]
    steps:
      - uses: actions/checkout@v3
      - uses: AxendoNL/sync-changes-from-cloud-action@v8.1
        with:
          cloud-repository-url: 'https://${{secrets.umbraco-cloud-username}}:${{secrets.umbraco-cloud-password}}@${{secrets.cloud-repository-url}}'
          web-directory: ${{inputs.web-directory}}
  Cleanup:
    if: ${{ always() }}
    needs: Synchronize
    runs-on: [self-hosted, axendo]
    steps:
      - uses: AxendoNL/sync-cleanup-action@v8