name: Synchronize cloud changes

on:
  workflow_call:

jobs:
  Synchronize:
    name: Synchronize
    runs-on: [self-hosted, axendo]
    steps:
      - uses: actions/checkout@v3
      - uses: AxendoNL/sync-changes-from-cloud-action@v9.1
        with:
          cloud-repository-url:  'https://${{secrets.UMBRACO_CLOUD_USERNAME}}:${{secrets.UMBRACO_CLOUD_PASSWORD}}@${{secrets.CLOUD_REPOSITORY_URL}}'
          from-dir: ../cloud-repository
          to-dir: ./
          token: ${{ secrets.NUGET_PAT }}
  Cleanup:
    if: ${{ always() }}
    needs: Synchronize
    runs-on: [self-hosted, axendo]
    steps:
      - name: Delete sync folder en files
        uses: AxendoNL/sync-cleanup-action@v9
      - name: Delete GitHub workspace
        run: Remove-Item -Recurse -Force ./*
