name: Synchronize cloud changes

on:
  workflow_call:
    secrets:
      cloud-repository-url:
        required: true
      umbraco-cloud-username:
        required: true
      umbraco-cloud-password:
        required: true
      umbraco-cloud-token:
        required: true

jobs:
  Synchronize:
    name: Synchronize
    runs-on: [self-hosted, axendo]
    steps:
      - uses: actions/checkout@v3
      - uses: AxendoNL/sync-changes-from-cloud-action@v9.1
        with:
          cloud-repository-url: 'https://${{secrets.umbraco-cloud-username}}:${{secrets.umbraco-cloud-password}}@${{secrets.cloud-repository-url}}'
          from-dir: ../cloud-repository
          to-dir: ./
          token: secrets.umbraco-cloud-token
  Cleanup:
    if: ${{ always() }}
    needs: Synchronize
    runs-on: [self-hosted, axendo]
    steps:
      - uses: AxendoNL/sync-cleanup-action@v9